- name: backend configuration
  hosts: backend
  become: yes
  tasks:
  - name: Disable node js
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable node js
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install node js
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: Add user Expense
    ansible.builtin.user:
      name: expense
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: extract the code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
  